CREATE TABLE IF NOT EXISTS `gateway_transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `order_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int NOT NULL,
  `user_mob` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount` decimal(10,2) NOT NULL DEFAULT '10.00',
  `payment_type` enum('activation','add_money') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'activation',
  `status` enum('pending','completed','failed','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `txn_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `utr` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_url` text COLLATE utf8mb4_unicode_ci,
  `remark1` text COLLATE utf8mb4_unicode_ci,
  `remark2` text COLLATE utf8mb4_unicode_ci,
  `date_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_id` (`order_id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
